const ActionTypes = {
  //users
  USERS_ALL_REQ: 'USERS_ALL_REQ',
  USERS_ALL_OK: 'USERS_ALL_OK',
  USERS_ALL_X: 'USERS_ALL_X',


  USERS_GETBYID_REQ: 'USERS_GETBYID_REQ',
  USERS_GETBYID_OK: 'USERS_GETBYID_OK',
  USERS_GETBYID_X: 'USERS_GETBYID_X',

  // Next below here

  // EventTypes
  EVENTTYPES_ALL_REQ: 'EVENTTYPES_ALL_REQ',
  EVENTTYPES_ALL_OK: 'EVENTTYPES_ALL_OK',
  EVENTTYPES_ALL_X: 'EVENTTYPES_ALL_X',


  //UrgencyTypes
  URGENCYTYPES_ALL_REQ: 'URGENCYTYPES_ALL_REQ',
  URGENCYTYPES_ALL_OK: 'URGENCYTYPES_ALL_OK',
  URGENCYTYPES_ALL_X: 'URGENCYTYPES_ALL_X',  


  // locationTypes
  LOCATIONTYPES_ALL_REQ: 'LOCATIONTYPES_ALL_REQ',
  LOCATIONTYPES_ALL_OK: 'LOCATIONTYPES_ALL_OK',
  LOCATIONTYPES_ALL_X: 'LOCATIONTYPES_ALL_X',
};

export default ActionTypes;
