const ActionTypes = {

  // area
  AREAS_ALL_REQ: 'AREAS_ALL_REQ',
  AREAS_ALL_OK: 'AREAS_ALL_OK',
  AREAS_ALL_X: 'AREAS_ALL_X',

  // areaUser

  // event

  // eventType
  EVENTTYPES_ALL_REQ: 'EVENTTYPES_ALL_REQ',
  EVENTTYPES_ALL_OK: 'EVENTTYPES_ALL_OK',
  EVENTTYPES_ALL_X: 'EVENTTYPES_ALL_X',

  EVENTTYPE_ADD_REQ: 'EVENTTYPE_ADD_REQ',
  EVENTTYPE_ADD_OK: 'EVENTTYPE_ADD_OK',
  EVENTTYPE_ADD_X: 'EVENTTYPE_ADD_X',

  EVENTTYPE_GETBYID_REQ: 'EVENTTYPE_GETBYID_REQ',
  EVENTTYPE_GETBYID_OK: 'EVENTTYPE_GETBYID_OK',
  EVENTTYPE_GETBYID_X: 'EVENTTYPE_GETBYID_X',

  EVENTTYPE_DELETE_REQ: 'EVENTTYPE_DELETE_REQ',
  EVENTTYPE_DELETE_OK: 'EVENTTYPE_DELETE_OK',
  EVENTTYPE_DELETE_X: 'EVENTTYPE_DELETE_X',

  // location
  LOCATIONS_ALL_REQ: 'LOCATIONS_ALL_REQ',
  LOCATIONS_ALL_OK: 'LOCATIONS_ALL_OK',
  LOCATIONS_ALL_X: 'LOCATIONS_ALL_X',

  LOCATION_GETBYID_REQ: 'LOCATION_GETBYID_REQ',
  LOCATION_GETBYID_OK: 'LOCATION_GETBYID_OK',
  LOCATION_GETBYID_X: 'LOCATION_GETBYID_X',

  LOCATION_DELETE_REQ: 'LOCATION_DELETE_REQ',
  LOCATION_DELETE_OK: 'LOCATION_DELETE_OK',
  LOCATION_DELETE_X: 'LOCATION_DELETE_X',

  // locationType
  LOCATIONTYPES_ALL_REQ: 'LOCATIONTYPE_ALL_REQ',
  LOCATIONTYPES_ALL_OK: 'LOCATIONTYPE_ALL_OK',
  LOCATIONTYPES_ALL_X: 'LOCATIONTYPE_ALL_X',

  LOCATIONTYPE_GETBYID_REQ: 'LOCATIONTYPE_GETBYID_REQ',
  LOCATIONTYPE_GETBYID_OK: 'LOCATIONTYPE_GETBYID_OK',
  LOCATIONTYPE_GETBYID_X: 'LOCATIONTYPE_GETBYID_X',

  LOCATIONTYPE_DELETE_REQ: 'LOCATIONTYPE_DELETE_REQ',
  LOCATIONTYPE_DELETE_OK: 'LOCATIONTYPE_DELETE_OK',
  LOCATIONTYPE_DELETE_X: 'LOCATIONTYPE_DELETE_X',

  // urgencyType
  URGENCYTYPES_ALL_REQ: 'URGENCYTYPES_ALL_REQ',
  URGENCYTYPES_ALL_OK: 'URGENCYTYPES_ALL_OK',
  URGENCYTYPES_ALL_X: 'URGENCYTYPES_ALL_X',

  // user
  USERS_ALL_REQ: 'USERS_ALL_REQ',
  USERS_ALL_OK: 'USERS_ALL_OK',
  USERS_ALL_X: 'USERS_ALL_X',

  USER_GETBYID_REQ: 'USER_GETBYID_REQ',
  USER_GETBYID_OK: 'USER_GETBYID_OK',
  USER_GETBYID_X: 'USER_GETBYID_X',
};

export default ActionTypes;
