const ActionTypes = {

  // area
  AREAS_ALL_REQ: 'AREAS_ALL_REQ',
  AREAS_ALL_OK: 'AREAS_ALL_OK',
  AREAS_ALL_X: 'AREAS_ALL_X',

  // areaUser
  AREA_USER_ALL_REQ: 'AREA_USER_ALL_REQ',
  AREA_USER_ALL_OK: 'AREA_USER_ALL_OK',
  AREA_USER_ALL_X: 'AREA_USER_ALL_X',
  // event

  // eventType
  EVENTTYPES_ALL_REQ: 'EVENTTYPES_ALL_REQ',
  EVENTTYPES_ALL_OK: 'EVENTTYPES_ALL_OK',
  EVENTTYPES_ALL_X: 'EVENTTYPES_ALL_X',

  // location
  LOCATIONS_ALL_REQ: 'LOCATIONS_ALL_REQ',
  LOCATIONS_ALL_OK: 'LOCATIONS_ALL_OK',
  LOCATIONS_ALL_X: 'LOCATIONS_ALL_X',

  // locationType
  LOCATIONTYPES_ALL_REQ: 'LOCATIONTYPES_ALL_REQ',
  LOCATIONTYPES_ALL_OK: 'LOCATIONTYPES_ALL_OK',
  LOCATIONTYPES_ALL_X: 'LOCATIONTYPES_ALL_X',

  // urgencyType
  URGENCYTYPES_ALL_REQ: 'URGENCYTYPES_ALL_REQ',
  URGENCYTYPES_ALL_OK: 'URGENCYTYPES_ALL_OK',
  URGENCYTYPES_ALL_X: 'URGENCYTYPES_ALL_X',

  // user
  USERS_ALL_REQ: 'USERS_ALL_REQ',
  USERS_ALL_OK: 'USERS_ALL_OK',
  USERS_ALL_X: 'USERS_ALL_X',

  USER_GETBYID_REQ: 'USER_GETBYID_REQ',
  USER_GETBYID_OK: 'USER_GETBYID_OK',
  USER_GETBYID_X: 'USER_GETBYID_X',
};

export default ActionTypes;
